spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-reserva
          uri: lb://MS-RESERVA
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<remaining>.*), /$\{remaining}
        - id: ms-reserva
          uri: lb://MS-TRASPASOS
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<remaining>.*), /$\{remaining}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
server:
  port: 8081